name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Runs this workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # This checks out your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Sets up Docker for building

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-username/finance_tracker .
          docker push your-username/finance_tracker
